baseurl: '/'
permalink: pretty
title: 'Swiss Genomics Association'
motto: 'Science-backed guidelines.'

logo:
  mobile: "images/logo/logo_v2.svg"
  mobile_height: "33px"
  mobile_width: "33px"
  desktop: "images/logo/logo_v2.svg"
  desktop_height: "40px"
  desktop_width: "40px"
  # desktop_width: "120px"
  # 391 × 341

home: 
  limit_technologies: 6
  limit_releases: 6

collections:
  technologies:
    output: true
  team:
    output: true
  blog:
    output: true
    permalink: /blog/:name/
  release:
    output: true
    permalink: /release/:name/


defaults:
  - scope:
      path: ""
      type: "technologies"
    values:
      layout: "tech"
  - scope:
      path: ""
      type: "team"
    values:
      layout: "team"
  - scope:
      path: ""
      type: "publications"
    values:
      layout: "publication"
  - scope:
      path: ""
      type: "releases"
    values:
      layout: "page"

sass:
  style: compressed # possible values: nested expanded compact compressed

plugins:
  - jekyll-environment-variables

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
